#!/usr/bin/env python3
"""
One-shot offline scoring surface (no API) — denser analog of challenge-kit score.py.

Runs:
  1) Multi-strategy matrix (deterministic controls)
  2) Live multi-model matrix re-score (committed dirs)
  3) Prints a short disagreement / routing summary for mentors

Usage:
  python challenge/scripts/score.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def run(script: str) -> int:
    path = ROOT / "scripts" / script
    print(f"\n=== {script} ===\n")
    return subprocess.call([sys.executable, str(path)], cwd=str(ROOT.parent))


def main() -> int:
    codes = []
    codes.append(run("score_strategies.py"))
    codes.append(run("score_live_matrix.py"))
    print(
        "\n=== routing summary ===\n"
        "Offline strategies show keyword over-trigger vs closed-world discipline.\n"
        "Live matrix shows model disagreement on the same two snippets:\n"
        "  - full CMO + clean CSR is achievable on strong free legs\n"
        "  - under-extract and CSR false positives appear on other legs\n"
        "Implication: route disagreements and CSR-positive hits to human review;\n"
        "do not auto-merge single-model output. Corpus Artifact A (Jaccard 3.8%)\n"
        "makes the same point at 60-chunk scale (see docs/metrics.md).\n"
    )
    out = ROOT / "results" / "live" / "DISAGREEMENT.md"
    # regenerate short markdown from matrix if present
    matrix = ROOT / "results" / "live" / "matrix_scores.json"
    if matrix.is_file():
        import json

        data = json.loads(matrix.read_text(encoding="utf-8"))
        rows = data.get("models") or []
        lines = [
            "# Live multi-model disagreement (offline re-score)",
            "",
            "Generated by `challenge/scripts/score.py` / `score_live_matrix.py`. No API.",
            "",
            "| Model | CMO # | CSR |",
            "|-------|------:|-----|",
        ]
        for r in rows:
            csr = "PASS" if r.get("csr_pass") is True else ("FAIL" if r.get("csr_pass") is False else "?")
            lines.append(f"| `{r['model']}` | {r.get('cmo_count', 0)} | {csr} |")
        strong = [r["model"] for r in rows if r.get("cmo_count", 0) >= 3 and r.get("csr_pass") is True]
        fail = [r["model"] for r in rows if r.get("csr_pass") is False]
        under = [r["model"] for r in rows if r.get("cmo_count", 0) < 3]
        lines += [
            "",
            f"**Full CMO + CSR pass ({len(strong)}):** " + ", ".join(f"`{m}`" for m in strong),
            f"**CSR fail ({len(fail)}):** " + ", ".join(f"`{m}`" for m in fail),
            f"**CMO under-extract ({len(under)}):** " + ", ".join(f"`{m}`" for m in under),
            "",
            "## Why this matters",
            "",
            "All models saw the same challenge task. They disagree on recall and on the",
            "CSR negative control. That is a **review-routing** signal for Part II,",
            "not a license to trust any single free or commercial leg.",
            "",
        ]
        out.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"wrote {out}")
    return 0 if all(c == 0 for c in codes) else 1


if __name__ == "__main__":
    raise SystemExit(main())
